name: 'Flutter Android + IOS Debug'
on: push
jobs:
  job1:
    name: building apk file
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
        
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.github_token}}
        
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.7.8+hotfix.4'
      
      - name: Install dependencies
        working-directory: ./hello_github_actions_flutter
        run: flutter pub get
      
      - name: build apk
        working-directory: ./hello_github_actions_flutter
        run: flutter build apk
        
      - name: Upload apk to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: ./hello_github_actions_flutter/build/app/outputs/apk/release/app-release.apk
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Flutter_Github_Actions/Flutter_Github_Actions/hello_github_actions_flutter/build/app/outputs/apk/release/app-release.apk
          asset_name: android_apk_v1.0.${{ steps.buildnumber.outputs.build_number }}.apk
          tag: android_v1.0.${{ steps.buildnumber.outputs.build_number }}
          overwrite: true
        
  job2:
    name: building ipa file
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.github_token}}
        
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.7.8+hotfix.4'
      
      - name: Install dependencies
        working-directory: ./hello_github_actions_flutter
        run: flutter pub get
        
      - name: build ipa
        working-directory: ./hello_github_actions_flutter
        run: flutter build ios --no-codesign --debug
        
      - name: Upload runner.app to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: /Users/runner/runners/2.161.0/work/Flutter_Github_Actions/Flutter_Github_Actions/hello_github_actions_flutter/build/ios/iphoneos/Runner.app

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /Users/runner/runners/2.161.0/work/Flutter_Github_Actions/Flutter_Github_Actions/hello_github_actions_flutter/build/ios/iphoneos/Runner.app
          asset_name: ios_app_v1.0.${{ steps.buildnumber.outputs.build_number }}.apk
          tag: ios_v1.0.${{ steps.buildnumber.outputs.build_number }}
          overwrite: true         

